### ISSUE TITLE
支持外接显示器

### ISSUE THREAD

**Issue by jyi2ya** [vaaandark/auto-backlight-sh#1]
现有的代码无法设置外接显示器的亮度。

[ddcutil](http://www.ddcutil.com/) 工具能通过 [Display Data Channel](https://en.wikipedia.org/wiki/Display_Data_Channel) 调整外接显示器的参数，包括亮度。例如，`ddcutil setvcp 10 + 5` 可以将屏幕亮度提高 5 个单位。

对于不支持 DDC 的屏幕，可以使用 `xrandr(1)` 工具的 `brigntness` 参数软件模拟。

```plain
       --brightness brightness
              Multiply the gamma values on the crtc currently  attached  to  the  output  to
              specified  floating  value.  Useful  for  overly bright or overly dim outputs.
              However, this is a software only modification, if your hardware has support to
              actually change the brightness, you will probably prefer to use xbacklight.
```

例如，`xrandr --output DisplayPort-0 --brightness 0.75` 可将 `DisplayPort-0` 的亮度设置为最大值的 0.75。

**Comment by vaaandark** [comment]
这个项目的功能是为带有光线传感器的笔记本电脑提供的（尤其是联想笔记本），一般需要根据环境亮度调节屏幕亮度的场景都是只使用笔记本自带屏幕。
当笔记本使用者在使用外接显示器的时候，我无法假设他们的光线传感器正好处于合适的位置，例如我的使用喜欢就是在使用外接显示器的时候不使用笔记本显示器并将笔记本合上，如此一来光线传感器便失去了其作用。
另外，使用外接显示器是工作环境相对固定的情景，使用者可以只对屏幕亮度进行一次调节，之后可以不再操心。如果此时的环境亮度发生了变化，使用者一般可以去调节环境光线使之利于工作学习，而不是需要脚本自动调节亮度。

PS: 谢谢你的 issue ，但是我要关掉它了
